using LogisticManagementApp.Models.CompanyPortal.Assets.Air;
using LogisticManagementApp.Models.CompanyPortal.Assets.CargoUnits;
using LogisticManagementApp.Models.CompanyPortal.Assets.Rail;
using LogisticManagementApp.Models.CompanyPortal.Assets.Road;
using LogisticManagementApp.Models.CompanyPortal.Assets.Sea;
using LogisticManagementApp.Models.CompanyPortal.Billing;
using LogisticManagementApp.Models.CompanyPortal.Branches;
using LogisticManagementApp.Models.CompanyPortal.Documents;
using LogisticManagementApp.Models.CompanyPortal.Operations;
using LogisticManagementApp.Models.CompanyPortal.Orders;
using LogisticManagementApp.Models.CompanyPortal.Pricing;
using LogisticManagementApp.Models.CompanyPortal.Routes;
using LogisticManagementApp.Models.CompanyPortal.Shipments;
using LogisticManagementApp.Models.CompanyPortal.Shipments.Legs;
using LogisticManagementApp.Models.CompanyPortal.Shipments.Packages;
using Microsoft.EntityFrameworkCore;
using System.Reflection;

namespace LogisticManagementApp.Applicationn.Services.CompanyPortal
{
    public partial class CompanyPortalService
    {
        public async Task PrepareAutoGeneratedFieldsAsync(Guid companyId, object model, bool isEdit)
        {
            EnsureGeneratedGuidId(model, isEdit);

            switch (model)
            {
                case null:
                    return;

                // Edit models first because many of them inherit from Create models.
                case CompanyBranchEditViewModel m:
                    m.BranchCode = await GetExistingStringAsync(_dbContext.CompanyBranches.Where(x => x.CompanyId == companyId && x.Id == m.Id).Select(x => x.BranchCode));
                    break;
                case CompanyBranchCreateViewModel m:
                    m.BranchCode = await GenerateCodeAsync(_dbContext.CompanyBranches.Where(x => x.CompanyId == companyId).Select(x => x.BranchCode!), "BRN");
                    break;

                case CompanyOrderEditViewModel m:
                    m.OrderNo = await GetExistingStringAsync(_dbContext.Orders.Where(x => x.CustomerCompanyId == companyId && x.Id == m.Id).Select(x => x.OrderNo));
                    break;
                case CompanyOrderCreateViewModel m:
                    SetStringProperty(m, nameof(CompanyOrderEditViewModel.OrderNo), await _numberGenerator.GenerateOrderNoAsync());
                    break;

                case CompanyOrderLineEditViewModel m:
                    m.LineNo = await GetExistingIntAsync(_dbContext.OrderLines.Where(x => x.Id == m.Id).Select(x => x.LineNo));
                    break;
                case CompanyOrderLineCreateViewModel m when m.OrderId != Guid.Empty:
                    m.LineNo = await GetNextIntAsync(_dbContext.OrderLines.Where(x => x.OrderId == m.OrderId).Select(x => (int?)x.LineNo));
                    break;

                case CompanyShipmentEditViewModel m:
                    m.ShipmentNo = await GetExistingStringAsync(_dbContext.Shipments.Where(x => x.CustomerCompanyId == companyId && x.Id == m.Id).Select(x => x.ShipmentNo));
                    break;
                case CompanyShipmentCreateViewModel m:
                    m.ShipmentNo = await _numberGenerator.GenerateShipmentNoAsync();
                    break;

                case CompanyShipmentLegEditViewModel m:
                    m.LegNo = await GetExistingIntAsync(_dbContext.ShipmentLegs.Where(x => x.Id == m.Id).Select(x => x.LegNo));
                    break;
                case CompanyShipmentLegCreateViewModel m when m.ShipmentId != Guid.Empty:
                    m.LegNo = await GetNextIntAsync(_dbContext.ShipmentLegs.Where(x => x.ShipmentId == m.ShipmentId).Select(x => (int?)x.LegNo));
                    break;

                case CompanyPackageEditViewModel m:
                    m.PackageNo = await GetExistingStringAsync(_dbContext.Packages.Where(x => x.Id == m.Id).Select(x => x.PackageNo));
                    break;
                case CompanyPackageCreateViewModel m:
                    m.PackageNo = await _numberGenerator.GeneratePackageNoAsync();
                    break;

                case AgreementEditViewModel m:
                    m.AgreementNumber = await GetExistingStringAsync(_dbContext.Agreements.Where(x => x.CompanyId == companyId && x.Id == m.Id).Select(x => x.AgreementNumber));
                    break;
                case AgreementCreateViewModel m:
                    m.AgreementNumber = await GenerateCodeAsync(_dbContext.Agreements.Where(x => x.CompanyId == companyId).Select(x => x.AgreementNumber), "AGR");
                    break;

                case PricingQuoteEditViewModel m:
                    m.QuoteNumber = await GetExistingStringAsync(_dbContext.PricingQuotes.Where(x => x.CustomerCompanyId == companyId && x.Id == m.Id).Select(x => x.QuoteNumber));
                    break;
                case PricingQuoteCreateViewModel m:
                    m.QuoteNumber = await GenerateCodeAsync(_dbContext.PricingQuotes.Where(x => x.CustomerCompanyId == companyId).Select(x => x.QuoteNumber), "QUO");
                    break;

                case PricingQuoteLineEditViewModel m:
                    m.LineNo = await GetExistingIntAsync(_dbContext.PricingQuoteLines.Where(x => x.Id == m.Id).Select(x => x.LineNo));
                    break;
                case PricingQuoteLineCreateViewModel m when m.PricingQuoteId != Guid.Empty:
                    m.LineNo = await GetNextIntAsync(_dbContext.PricingQuoteLines.Where(x => x.PricingQuoteId == m.PricingQuoteId).Select(x => (int?)x.LineNo));
                    break;

                case ChargeEditViewModel m:
                    m.ChargeCode = await GetExistingStringAsync(_dbContext.Charges.Where(x => x.Id == m.Id).Select(x => x.ChargeCode));
                    break;
                case ChargeCreateViewModel m:
                    m.ChargeCode = await GenerateCodeAsync(_dbContext.Charges.Select(x => x.ChargeCode), "CHG");
                    break;

                case InvoiceEditViewModel m:
                    m.InvoiceNo = await GetExistingStringAsync(_dbContext.Invoices.Where(x => x.BillToCompanyId == companyId && x.Id == m.Id).Select(x => x.InvoiceNo));
                    break;
                case InvoiceCreateViewModel m:
                    m.InvoiceNo = await GenerateCodeAsync(_dbContext.Invoices.Where(x => x.BillToCompanyId == companyId).Select(x => x.InvoiceNo), "INV");
                    break;

                case InvoiceLineEditViewModel m:
                    m.LineNo = await GetExistingIntAsync(_dbContext.InvoiceLines.Where(x => x.Id == m.Id).Select(x => x.LineNo));
                    break;
                case InvoiceLineCreateViewModel m when m.InvoiceId != Guid.Empty:
                    m.LineNo = await GetNextIntAsync(_dbContext.InvoiceLines.Where(x => x.InvoiceId == m.InvoiceId).Select(x => (int?)x.LineNo));
                    break;

                case CreditNoteEditViewModel m:
                    m.CreditNoteNo = await GetExistingStringAsync(_dbContext.CreditNotes.Where(x => x.BillToCompanyId == companyId && x.Id == m.Id).Select(x => x.CreditNoteNo));
                    break;
                case CreditNoteCreateViewModel m:
                    m.CreditNoteNo = await GenerateCodeAsync(_dbContext.CreditNotes.Where(x => x.BillToCompanyId == companyId).Select(x => x.CreditNoteNo), "CRN");
                    break;

                case DocumentEditViewModel m:
                    m.DocumentNo = await GetExistingStringAsync(_dbContext.Documents.Where(x => x.Id == m.Id).Select(x => x.DocumentNo));
                    break;
                case DocumentCreateViewModel m:
                    m.DocumentNo = await GenerateCodeAsync(_dbContext.Documents.Where(x => x.Shipment.CustomerCompanyId == companyId).Select(x => x.DocumentNo!), "DOC");
                    break;

                case DocumentVersionEditViewModel m:
                    m.VersionNo = await GetExistingIntAsync(_dbContext.DocumentVersions.Where(x => x.Id == m.Id).Select(x => x.VersionNo));
                    break;
                case DocumentVersionCreateViewModel m when m.DocumentId != Guid.Empty:
                    m.VersionNo = await GetNextIntAsync(_dbContext.DocumentVersions.Where(x => x.DocumentId == m.DocumentId).Select(x => (int?)x.VersionNo));
                    break;

                case BookingEditViewModel m:
                    m.BookingNo = await GetExistingStringAsync(_dbContext.Bookings.Where(x => x.Id == m.Id).Select(x => x.BookingNo));
                    break;
                case BookingCreateViewModel m:
                    m.BookingNo = await GenerateCodeAsync(_dbContext.Bookings.Select(x => x.BookingNo), "BKG");
                    break;

                case BookingLegEditViewModel m:
                    m.LegNo = await GetExistingIntAsync(_dbContext.BookingLegs.Where(x => x.Id == m.Id).Select(x => x.LegNo));
                    break;
                case BookingLegCreateViewModel m when m.BookingId != Guid.Empty:
                    m.LegNo = await GetNextIntAsync(_dbContext.BookingLegs.Where(x => x.BookingId == m.BookingId).Select(x => (int?)x.LegNo));
                    break;

                case RouteEditViewModel m:
                    m.RouteCode = await GetExistingStringAsync(_dbContext.Routes.Where(x => x.CompanyId == companyId && x.Id == m.Id).Select(x => x.RouteCode));
                    break;
                case RouteCreateViewModel m:
                    m.RouteCode = await GenerateCodeAsync(_dbContext.Routes.Where(x => x.CompanyId == companyId).Select(x => x.RouteCode), "RTE");
                    break;

                case RouteStopEditViewModel m:
                    m.SequenceNo = await GetExistingIntAsync(_dbContext.RouteStops.Where(x => x.Id == m.Id).Select(x => x.SequenceNo));
                    break;
                case RouteStopCreateViewModel m when m.RouteId != Guid.Empty:
                    m.SequenceNo = await GetNextIntAsync(_dbContext.RouteStops.Where(x => x.RouteId == m.RouteId).Select(x => (int?)x.SequenceNo));
                    break;

                case VehicleEditViewModel m:
                    m.RegistrationNumber = await GetExistingStringAsync(_dbContext.Vehicles.Where(x => x.CompanyId == companyId && x.Id == m.Id).Select(x => x.RegistrationNumber));
                    break;
                case VehicleCreateViewModel m:
                    m.RegistrationNumber = await GenerateCodeAsync(_dbContext.Vehicles.Where(x => x.CompanyId == companyId).Select(x => x.RegistrationNumber), "VEH");
                    break;

                case TripEditViewModel m:
                    m.TripNo = await GetExistingStringAsync(_dbContext.Trips.Where(x => x.Id == m.Id).Select(x => x.TripNo));
                    break;
                case TripCreateViewModel m:
                    m.TripNo = await GenerateCodeAsync(_dbContext.Trips.Select(x => x.TripNo), "TRP");
                    break;

                case TripStopEditViewModel m:
                    m.SequenceNumber = await GetExistingIntAsync(_dbContext.TripStops.Where(x => x.Id == m.Id).Select(x => x.SequenceNumber));
                    break;
                case TripStopCreateViewModel m when m.TripId != Guid.Empty:
                    m.SequenceNumber = await GetNextIntAsync(_dbContext.TripStops.Where(x => x.TripId == m.TripId).Select(x => (int?)x.SequenceNumber));
                    break;

                case AircraftEditViewModel m:
                    m.TailNumber = await GetExistingStringAsync(_dbContext.Aircraft.Where(x => x.CompanyId == companyId && x.Id == m.Id).Select(x => x.TailNumber));
                    break;
                case AircraftCreateViewModel m:
                    m.TailNumber = await GenerateCodeAsync(_dbContext.Aircraft.Where(x => x.CompanyId == companyId).Select(x => x.TailNumber), "AIR");
                    break;

                case FlightEditViewModel m:
                    m.FlightNumber = await GetExistingStringAsync(_dbContext.Flights.Where(x => x.Id == m.Id).Select(x => x.FlightNumber));
                    break;
                case FlightCreateViewModel m:
                    m.FlightNumber = await GenerateCodeAsync(_dbContext.Flights.Select(x => x.FlightNumber), "FLT");
                    break;

                case FlightSegmentEditViewModel m:
                    m.SegmentNo = await GetExistingIntAsync(_dbContext.FlightSegments.Where(x => x.Id == m.Id).Select(x => x.SegmentNo));
                    break;
                case FlightSegmentCreateViewModel m when m.FlightId != Guid.Empty:
                    m.SegmentNo = await GetNextIntAsync(_dbContext.FlightSegments.Where(x => x.FlightId == m.FlightId).Select(x => (int?)x.SegmentNo));
                    break;

                case UldEditViewModel m:
                    m.UldNumber = await GetExistingStringAsync(_dbContext.ULDs.Where(x => x.OwnerCompanyId == companyId && x.Id == m.Id).Select(x => x.UldNumber));
                    break;
                case UldCreateViewModel m:
                    m.UldNumber = await GenerateCodeAsync(_dbContext.ULDs.Where(x => x.OwnerCompanyId == companyId).Select(x => x.UldNumber), "ULD");
                    break;

                case TrainEditViewModel m:
                    m.TrainNumber = await GetExistingStringAsync(_dbContext.Trains.Where(x => x.CompanyId == companyId && x.Id == m.Id).Select(x => x.TrainNumber));
                    break;
                case TrainCreateViewModel m:
                    m.TrainNumber = await GenerateCodeAsync(_dbContext.Trains.Where(x => x.CompanyId == companyId).Select(x => x.TrainNumber), "TRN");
                    break;

                case RailCarEditViewModel m:
                    m.RailCarNumber = await GetExistingStringAsync(_dbContext.RailCars.Where(x => x.CompanyId == companyId && x.Id == m.Id).Select(x => x.RailCarNumber));
                    break;
                case RailCarCreateViewModel m:
                    m.RailCarNumber = await GenerateCodeAsync(_dbContext.RailCars.Where(x => x.CompanyId == companyId).Select(x => x.RailCarNumber), "RCL");
                    break;

                case RailServiceEditViewModel m:
                    m.ServiceCode = await GetExistingStringAsync(_dbContext.RailServices.Where(x => x.Id == m.Id).Select(x => x.ServiceCode));
                    break;
                case RailServiceCreateViewModel m:
                    m.ServiceCode = await GenerateCodeAsync(_dbContext.RailServices.Select(x => x.ServiceCode), "RSC");
                    break;

                case RailMovementEditViewModel m:
                    m.MovementNo = await GetExistingStringAsync(_dbContext.RailMovements.Where(x => x.Id == m.Id).Select(x => x.MovementNo));
                    break;
                case RailMovementCreateViewModel m:
                    m.MovementNo = await GenerateCodeAsync(_dbContext.RailMovements.Select(x => x.MovementNo), "RMV");
                    break;

                case ContainerEditViewModel m:
                    m.ContainerNumber = await GetExistingStringAsync(_dbContext.Containers.Where(x => x.Id == m.Id).Select(x => x.ContainerNumber));
                    break;
                case ContainerCreateViewModel m:
                    m.ContainerNumber = await GenerateCodeAsync(_dbContext.Containers.Select(x => x.ContainerNumber), "CNT");
                    break;

                case ContainerSealEditViewModel m:
                    m.SealNumber = await GetExistingStringAsync(_dbContext.ContainerSeals.Where(x => x.Id == m.Id).Select(x => x.SealNumber));
                    break;
                case ContainerSealCreateViewModel m:
                    m.SealNumber = await GenerateCodeAsync(_dbContext.ContainerSeals.Select(x => x.SealNumber), "CSL");
                    break;

                case VesselEditViewModel m:
                    m.ImoNumber = await GetExistingStringAsync(_dbContext.Vessels.Where(x => x.CompanyId == companyId && x.Id == m.Id).Select(x => x.ImoNumber));
                    break;
                case VesselCreateViewModel m:
                    m.ImoNumber = await GenerateCodeAsync(_dbContext.Vessels.Where(x => x.CompanyId == companyId).Select(x => x.ImoNumber!), "IMO");
                    break;

                case VoyageEditViewModel m:
                    m.VoyageNumber = await GetExistingStringAsync(_dbContext.Voyages.Where(x => x.Id == m.Id).Select(x => x.VoyageNumber));
                    break;
                case VoyageCreateViewModel m:
                    m.VoyageNumber = await GenerateCodeAsync(_dbContext.Voyages.Select(x => x.VoyageNumber), "VOY");
                    break;

                case VoyageStopEditViewModel m:
                    m.SequenceNumber = await GetExistingIntAsync(_dbContext.VoyageStops.Where(x => x.Id == m.Id).Select(x => x.SequenceNumber));
                    break;
                case VoyageStopCreateViewModel m when m.VoyageId != Guid.Empty:
                    m.SequenceNumber = await GetNextIntAsync(_dbContext.VoyageStops.Where(x => x.VoyageId == m.VoyageId).Select(x => (int?)x.SequenceNumber));
                    break;
            }
        }


        private static void EnsureGeneratedGuidId(object? model, bool isEdit)
        {
            if (model == null || isEdit)
                return;

            var property = model.GetType().GetProperty("Id", BindingFlags.Public | BindingFlags.Instance);
            if (property == null || !property.CanWrite)
                return;

            var clrType = Nullable.GetUnderlyingType(property.PropertyType) ?? property.PropertyType;
            if (clrType != typeof(Guid))
                return;

            var currentValue = property.GetValue(model);
            if (currentValue is Guid guidValue && guidValue != Guid.Empty)
                return;

            property.SetValue(model, Guid.NewGuid());
        }

        private static void SetStringProperty(object model, string propertyName, string value)
        {
            var property = model.GetType().GetProperty(propertyName, BindingFlags.Public | BindingFlags.Instance);
            if (property != null && property.CanWrite && property.PropertyType == typeof(string))
            {
                property.SetValue(model, value);
            }
        }

        private async Task<string> GenerateCodeAsync(IQueryable<string> source, string prefix)
        {
            var year = DateTime.UtcNow.Year;
            return await GenerateSequentialStringAsync(source, $"{prefix}-{year}-");
        }

        private async Task<string> GenerateSequentialStringAsync(IQueryable<string> source, string prefix)
        {
            var existing = await source
                .IgnoreQueryFilters()
                .Where(x => x != null && x.StartsWith(prefix))
                .ToListAsync();

            var next = existing
                .Select(x => x[prefix.Length..])
                .Where(x => int.TryParse(x, out _))
                .Select(int.Parse)
                .DefaultIfEmpty(0)
                .Max() + 1;

            return $"{prefix}{next:D6}";
        }

        private static async Task<string> GetExistingStringAsync(IQueryable<string?> source)
            => (await source.FirstOrDefaultAsync()) ?? string.Empty;

        private static async Task<int> GetExistingIntAsync(IQueryable<int> source)
            => await source.FirstOrDefaultAsync();

        private static async Task<int> GetNextIntAsync(IQueryable<int?> source)
            => (await source.MaxAsync() ?? 0) + 1;
    }
}
